import type { Metadata } from 'next'
import { Inter, Geist } from 'next/font/google'
import './globals.css'
import ThemeInitializer from './theme-initializer'
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={cn("font-sans", geist.variable)}>
      <ThemeInitializer />
      <body className={inter.className}>{children}</body>
    </html>
  )
}
